Question 1: Which of the below best describes Scikit-learn?

**Answer: A Python library providing tools for machine learning**

Question 2: Scikit-learn provides access to a number of datasets. We will work with the iris dataset.
What type of object is iris?

In [4]:
from sklearn.datasets import load_iris
iris = load_iris()
print(type(iris))

<class 'sklearn.utils._bunch.Bunch'>


Question 3: The iris object has 8 attributes. Which attribute contains a description of the iris dataset?

In [5]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

Question 4: Print the description attribute of iris and read about the data. What domain is this data drawn from?

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

Question 5: What does a single observation (row) in the iris dataset represent?

In [7]:
print(iris.data)
print(iris.target)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Question 6: We need to create a Pandas DataFrame to hold the iris dataset. Read iris.DESCR and inspect the type of iris's other attributes.

What steps must we take to create a Pandas DataFrame?

In [8]:
import pandas as pd
# Create a DataFrame for features
df_features = pd.DataFrame(iris.data, columns=iris.feature_names)

# Create a Series for the target values (species)
df_target = pd.Series(iris.target, name="species")

# Combine them using pd.concat along axis=1 (column-wise)
df = pd.concat([df_features, df_target], axis=1)

# Display the DataFrame
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0  


Question 7: What are the dimensions of the complete iris DataFrame?

In [12]:
print(df.shape)

(150, 5)


Question 8: Compare iris.DESCR to iris.target. Can you figure out how to map the encoding in iris.target to the species names?

In [9]:
#print(iris.target_names)
#print(iris.target)

df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["species"] = iris.target
df["species_name"] = df["species"].apply(lambda x: iris.target_names[x])

print(df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species species_name  

Question 9: We have measurements for sepal length and width, and measurements for petal length and width.

Suppose we want to compare a flower's sepals with its petals using some notion of "total size".

We don't have enough information to calculate volumes, so will simplify drastically by assuming sepals and petals are 2d rectangles.

What is the Pearson correlation between the sepal area and petal area?

In [10]:
df["sepal_area"] = df["sepal length (cm)"] * df["sepal width (cm)"]
df["petal_area"] = df["petal length (cm)"] * df["petal width (cm)"]

pearson_corr = df["sepal_area"].corr(df["petal_area"])
print("Pearson Correlation:", pearson_corr)

Pearson Correlation: 0.4545033351745463


Question 10: Which scatter plot below would produce a correlation close to the one you calculated for sepal area vs petal area?

**Answer: Choice 3**

Question 11: There is a hypothesis test associated with the Pearson correlation. It is called Pearson correlation significance test. The test has null/alternative hypotheses and significance is decided by evaluating a p-value.

If you run this test at a significance threshold of 0.05 and the p-value is 0.4, what does this mean?

**Answer: We fail to reject the null hypothesis that the population correlation is 0.**

Question 12: Pearson correlation comes in handy when we are comparing 2 continuous variables. What if we want to compare a continuous variable across a categorical variable with 2 levels?

For example, suppose we wanted to know how sepal length varies across flowers that are either Virginica or not-Virginica. Which techniques below could possibly apply?

**Answer: Two-Sample Unpaired t-Test**

Question 13: What coding approach can we take to create a new column in our DataFrame that is equal to 1 if the observation is a Virginica, and 0 otherwise?

In [12]:
import numpy as np
df["is_virginica"] = np.where(df["species_name"] == "virginica", 1, 0)
df["is_virginica_2"] = df["species_name"].map(lambda x: 1 if x == "virginica" else 0)
print(df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species species_name  

Question 14: Create two Pandas.Series objects. One should contain sepal length measurements for Virginica flowers, and the other should contain the same for non-Virginica flowers.

Conduct a two sample unpaired t-test using this data. Which number below is the closest to the p-value for this test?This question is required.

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.datasets import load_iris

iris = load_iris()

df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["species"] = iris.target

species_names = dict(enumerate(iris.target_names))
df["species_name"] = df["species"].map(species_names)

virginica = df[df["species_name"] == "virginica"]["sepal length (cm)"]
not_virginica = df[df["species_name"] != "virginica"]["sepal length (cm)"]

t_stat, p_value = stats.ttest_ind(virginica, not_virginica, equal_var=False)

print(f"T-Statistic: {t_stat:.4f}")
print(f"P-Value: {p_value:.4f}")

alpha = 0.05  # Significance level
if p_value < alpha:
    print("🔹 Reject the null hypothesis: Significant difference in sepal length.")
else:
    print("🔹 Fail to reject the null hypothesis: No significant difference in sepal length.")


T-Statistic: 10.1109
P-Value: 0.0000
🔹 Reject the null hypothesis: Significant difference in sepal length.


Question 15: What if we want to compare sepal length across all 3 species? Which models can we use?

**Answer: Analysis of Variance (ANOVA)**



Question 16: We want to answer this question about the data:

"What is the relationship between sepal length and Iris species?"

With this question in mind, why is Linear Regression a more powerful approach compared to ANOVA?

**Answer: Linear Regression can provide coefficients that quantify the change in sepal length for different Iris species**

Question 17: Use the f_oneway function from the scipy.stats module to perform an ANOVA on sepal length by species.

What is the F-statistic for this ANOVA?

In [2]:
import pandas as pd
from scipy.stats import f_oneway
from sklearn.datasets import load_iris

iris = load_iris()

df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["species"] = iris.target

species_names = dict(enumerate(iris.target_names))
df["species_name"] = df["species"].map(species_names)

setosa = df[df["species_name"] == "setosa"]["sepal length (cm)"]
versicolor = df[df["species_name"] == "versicolor"]["sepal length (cm)"]
virginica = df[df["species_name"] == "virginica"]["sepal length (cm)"]

f_stat, p_value = f_oneway(setosa, versicolor, virginica)

print(f"F-Statistic: {f_stat:.4f}")
print(f"P-Value: {p_value:.10f}")

alpha = 0.05  # Significance level
if p_value < alpha:
    print("🔹 Reject the null hypothesis: Sepal length differs significantly among species.")
else:
    print("🔹 Fail to reject the null hypothesis: No significant difference in sepal length.")


F-Statistic: 119.2645
P-Value: 0.0000000000
🔹 Reject the null hypothesis: Sepal length differs significantly among species.


Question 18: Consider that:
1) The null hypothesis for ANOVA is that there's no difference in the means between groups.
2) The F statistic is (roughly) the difference between groups divided by the difference within groups.

Keeping the above in mind, what is the relationship between the F statistic and the p-value?
In our ANOVA, groups refers to species.

**Answer: As the F statistic goes up, the p-value goes down.**

Question 19: We want to make a linear regression model to predict sepal length as a function of Iris species.

sepal length = f(species)

By default species is encoded as either 0, 1 or 2. This means our regression formula is:

sepal length = intercept + slope*species

Right?

**Answer: No, the numerical encoding doesn't make sense since there's no inherent order to the Iris species.**

Question 20: What does pandas.get_dummies do?

**Answer: It generates binary variables (0 or 1) for each category of a categorical variable.**

Question 21: Imagine we will use N data points to fit a regression model to predict height as a function of handedness (left or right handed). We use indicator variable(s) for handedness, meaning our handedness column(s) will contain a 1 or a 0.

If we encode handedness using one variable, our X variable has dimensions (N,1) and we write our model as:

y = height = intercept + slope*right_handed = f(right_handed) = f(X)

If we encode handedness using two variables, our X variable has dimensions (N,2) and we write our model as:

y = height = intercept + slope_r*right_handed + slope_l*left_handed = f(right_handed, left_handed) = f(X)

The second one will throw an error. Why?

**Answer: Because the presence of both indicators creates a redundancy which makes it impossible for the model to estimate both slope terms accurately.**

Question 22: We want to make a linear regression model to predict sepal length as a function of Iris species.

y = sepal length = f(species) = f(X)

What are the shapes of sepal length (y) and species (X) in the formula above?

In [3]:
# ✅ Complete Code to Verify Shapes of y (sepal length) and X (species one-hot encoded with all categories)

import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()

df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["species"] = iris.target

species_names = dict(enumerate(iris.target_names))
df["species_name"] = df["species"].map(species_names)

df_encoded = pd.get_dummies(df, columns=["species_name"], drop_first=False)

y = df_encoded["sepal length (cm)"].values.reshape(-1, 1)  # Reshaping to (150,1)

X = df_encoded[["species_name_setosa", "species_name_versicolor", "species_name_virginica"]].values

y_shape = y.shape  # Shape of Sepal Length
X_shape = X.shape  # Shape of One-Hot Encoded Species

y_shape, X_shape


((150, 1), (150, 3))

Question 23: Fit a linear regression using the statsmodels library after making sure sepal length (y) and the species (X) have the correct shape.

In what neighborhood is the R-squared for this model?

In [5]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.datasets import load_iris

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["species"] = iris.target

# Map species numbers to names
species_names = dict(enumerate(iris.target_names))
df["species_name"] = df["species"].map(species_names)

# Apply One-Hot Encoding (Keep all categories)
df_encoded = pd.get_dummies(df, columns=["species_name"], drop_first=False)

# Define Target Variable (Sepal Length)
y = df_encoded["sepal length (cm)"].values.reshape(-1, 1)  # Reshape to (150,1)

# Define Predictor Variables (Species One-Hot Encoded with all categories)
X = df_encoded[["species_name_setosa", "species_name_versicolor", "species_name_virginica"]].values

# Convert any boolean values to integers (Fix TypeError)
X = X.astype(int)

# Add Constant for Intercept
X_sm = sm.add_constant(X)

# Fit OLS Regression Model
model = sm.OLS(y, X_sm).fit()

# Print Regression Summary
print(model.summary())


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.619
Model:                            OLS   Adj. R-squared:                  0.614
Method:                 Least Squares   F-statistic:                     119.3
Date:                Thu, 20 Feb 2025   Prob (F-statistic):           1.67e-31
Time:                        01:39:32   Log-Likelihood:                -111.73
No. Observations:                 150   AIC:                             229.5
Df Residuals:                     147   BIC:                             238.5
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.3825      0.032    139.020      0.0

Question 24: The coefficients (slope terms) in linear regression have a hypothesis test associated with them. The P>|t| column in the model summary gives us the p-value for each of these tests.

What is the null hypothesis for this hypothesis test?

**Answer: The true value of the coefficient is zero.**

Question 25: Let's say our sepal length model looks like this:

sepal length = 5 + .93*species_versicolor + 1.58*species_virginica

What is the maximum value of sepal length that our model can possibly give us?

In [6]:
# Define coefficients from the regression equation
intercept = 5
coef_versicolor = 0.93
coef_virginica = 1.58

# Compute sepal lengths for each species
sepal_length_setosa = intercept + (coef_versicolor * 0) + (coef_virginica * 0)
sepal_length_versicolor = intercept + (coef_versicolor * 1) + (coef_virginica * 0)
sepal_length_virginica = intercept + (coef_versicolor * 0) + (coef_virginica * 1)

# Determine the maximum sepal length
max_sepal_length = max(sepal_length_setosa, sepal_length_versicolor, sepal_length_virginica)

# Display results
print(f"Setosa Sepal Length: {sepal_length_setosa}")
print(f"Versicolor Sepal Length: {sepal_length_versicolor}")
print(f"Virginica Sepal Length: {sepal_length_virginica}")
print(f"Maximum Sepal Length: {max_sepal_length}")


Setosa Sepal Length: 5.0
Versicolor Sepal Length: 5.93
Virginica Sepal Length: 6.58
Maximum Sepal Length: 6.58
